- name: diffuse
  config:
    color: [0.725, 0.71, 0.68]
- name: diffuse
  config:
    color: [0.161, 0.133, 0.427]
- name: diffuse
  config:
    color: [0.630, 0.065, 0.05]
- name: diffuse
  config:
    color: [0.5, 0.5, 0.5]
- name: diffuse
  config:
    color: [0.5, 0.5, 0.5]
- name: diffuse
  config:
    color: [0.5, 0.5, 0.5]
