- name: diffuse
  config:
    color: [0, 0, 0]
- name: diffuse
  config:
    color: [0, 0, 0]
- name: diffuse
  config:
    color: [0, 0, 0]
- name: diffuse
  config:
    color: [0, 0, 0]
- name: diffuse
  config:
    color: [0, 0, 0]
- name: microfacet
  config:
    color: [0.0175, 0.0225, 0.0325]
    roughness: 0.005
- name: microfacet
  config:
    color: [0.0175, 0.0225, 0.0325]
    roughness: 0.02
- name: microfacet
  config:
    color: [0.0175, 0.0225, 0.0325]
    roughness: 0.05
- name: microfacet
  config:
    color: [0.0175, 0.0225, 0.0325]
    roughness: 0.1
- name: diffuse
  config:
    color: [0.1, 0.1, 0.1]
